name: Final
on:
  workflow_call:
  # push:
  #   branches:
  #     - main

jobs:
  get_release_job:  # Nombre del primer job
    uses: elBotija/testw/.github/workflows/b.yml@main  # Llamada al workflow 'b.yml' a nivel de jobs

  process_release_job:  # Segundo job
    runs-on: ubuntu-latest
    needs: get_release_job  # Dependencia del job anterior
    steps:
      - name: Access release variable
        run: echo "Release version is ${{ needs.get_release_job.outputs.release }}" 